### ISSUE TITLE
this project does not support python 2

### ISSUE THREAD

**Issue by 0hotpotman0** [Sensirion/python-i2c-sen5x#1]
Hi 
I follow your instruction and execute it on the raspberry pi 3 device, but it did not support python 2, the error as below: 

![image](https://user-images.githubusercontent.com/47217650/154896964-1ba91961-78cd-4de5-aaa9-6cc793c862c4.png)

then I try python  3,   it can download success. but after that, all commands can not work 
![image](https://user-images.githubusercontent.com/47217650/154897011-40d9bfea-da23-450a-a36d-8077eca8006b.png)

![image](https://user-images.githubusercontent.com/47217650/154897294-f691dab7-68db-468e-bf88-88f50b1a0dc2.png)

Could give some help, please.

Best regards

**Comment by psachs** [comment]
Python 2 support ended in January 2020 and will not receive any updates anymore (even security updates).
Therefore we will not support Python 2 in this driver or any upcoming drivers.

You are running flake8 and editorconfig with Python 2.7 and not Python 3, therefore the errors. They are not related to the SEN5x driver but your Python installation.

I highly recommend to use virtualenv to ensure a controlled Python environment:
`pip install virtualenv`

And then create a virtualenv for Python 3 and install / use the driver within this environment:

```bash
virtualenv -p /usr/bin/python3 v_env
. v_env/bin/activate
pip install -e.[test]
```
