### ISSUE TITLE
CircuitPython and potentially micropython for free

### ISSUE THREAD

**Issue by tyeth** [Sensirion/python-i2c-sen5x#3]
Hi, I want to use this library on embedded hardware, specifically in [adafruit's circuitpython](https://circuitpython.org). I have, so thanks for providing it to work with!

Now I want to share my work with the wider community, but the library name uses sensirion, so I guess I'm asking permission to use the name purely for the purposes of maintaining code compatibility.
I don't think my changes feed back to your repos very well, but here is a description of them:
[My fork](https://github.com/Sensirion/python-i2c-sen5x/compare/master...good-enough-technology:circuitpython-i2c-sen5x:master) ~~adds adafruit_platformdetect which~~ can switch logging to adafruit_circuitpython_logging if running circuitpython (checked via `sys.implementation.name`). There is [an additional fork](https://github.com/Sensirion/python-i2c-driver/compare/master...good-enough-technology:python-i2c-driver:master) of the python-i2c-driver repo with a new CircuitPythonI2cTransciever.py that uses adafruit_bus_device to provide i2c safely instead of the LinuxI2cTransciever as well as switching logging provider if needed. The code then works as is if you import an i2ctranceiver (auto-selects correct one) or the CircuitPythonI2cTransceiver and instantiate it then sen5x.

Thanks again for your assistance and help with this matter.

**Comment by varesio** [comment]
Hi @tyeth! 

This is really interesting work! We are always happy to see how the community is using our sensors and our resources!

You are free to use the name in your fork, please update only the Readme.MD so that it reflects that this is a fork and people are not confused :)
